split ci jobs to paralelize generated code verification

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,23 +30,92 @@ jobs:
       - name: Run all the linter tools against code
         run: make lint
 
-  gen:
-    name: Check generated files
+  gen-doc:
+    name: Check gen-doc generated files
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       
       - name: gen-doc
         run: make gen-doc
+        
+      - name: Check if generated files are up to date
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "❌ Error: Generated files are not up to date. Please run \`make gen\`."
+            echo "🚨 If \`make gen\` doesn't update the contract bytecodes and/or go bindings and this job is still failing, please take a look at the ethereum and foundry versions. We don't pin the versions of these packages in CI so this job may complain after an update of the packages!"
+            git status --porcelain
+            git diff
+            exit 1
+          else
+            echo "✅ Generated files are up to date."
+          fi
 
+  gen-proto:
+    name: Check gen-proto generated files
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      
       - name: gen-proto
         run: make gen-proto
 
+      - name: Check if generated files are up to date
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "❌ Error: Generated files are not up to date. Please run \`make gen\`."
+            echo "🚨 If \`make gen\` doesn't update the contract bytecodes and/or go bindings and this job is still failing, please take a look at the ethereum and foundry versions. We don't pin the versions of these packages in CI so this job may complain after an update of the packages!"
+            git status --porcelain
+            git diff
+            exit 1
+          else
+            echo "✅ Generated files are up to date."
+
+  gen-go-bindings:
+    name: Check gen-go-bindings generated files
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      
       - name: gen-go-bindings
         run: make gen-go-bindings
+        
+      - name: Check if generated files are up to date
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "❌ Error: Generated files are not up to date. Please run \`make gen\`."
+            echo "🚨 If \`make gen\` doesn't update the contract bytecodes and/or go bindings and this job is still failing, please take a look at the ethereum and foundry versions. We don't pin the versions of these packages in CI so this job may complain after an update of the packages!"
+            git status --porcelain
+            git diff
+            exit 1
+          else
+            echo "✅ Generated files are up to date."
+
+  gen-load-test-modes:
+    name: Check gen-load-test-modes generated files
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
 
       - name: gen-load-test-modes
         run: make gen-load-test-modes
+        
+      - name: Check if generated files are up to date
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "❌ Error: Generated files are not up to date. Please run \`make gen\`."
+            echo "🚨 If \`make gen\` doesn't update the contract bytecodes and/or go bindings and this job is still failing, please take a look at the ethereum and foundry versions. We don't pin the versions of these packages in CI so this job may complain after an update of the packages!"
+            git status --porcelain
+            git diff
+            exit 1
+          else
+            echo "✅ Generated files are up to date."
+
+  gen-json-rpc-types:
+    name: Check gen-json-rpc-types generated files
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
 
       - name: gen-json-rpc-types
         run: make gen-json-rpc-types
@@ -61,7 +130,6 @@ jobs:
             exit 1
           else
             echo "✅ Generated files are up to date."
-          fi
 
   test:
     name: Test
