make gen investigation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -57,17 +57,17 @@ jobs:
       - name: gen-json-rpc-types
         run: make gen-json-rpc-types 
         
-      # - name: Check if generated files are up to date
-      #   run: |
-      #     if [[ -n $(git status --porcelain) ]]; then
-      #       echo "❌ Error: Generated files are not up to date. Please run \`make gen\`."
-      #       echo "🚨 If \`make gen\` doesn't update the contract bytecodes and/or go bindings and this job is still failing, please take a look at the ethereum and foundry versions. We don't pin the versions of these packages in CI so this job may complain after an update of the packages!"
-      #       git status --porcelain
-      #       git diff
-      #       exit 1
-      #     else
-      #       echo "✅ Generated files are up to date."
-      #     fi
+      - name: Check if generated files are up to date
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "❌ Error: Generated files are not up to date. Please run \`make gen\`."
+            echo "🚨 If \`make gen\` doesn't update the contract bytecodes and/or go bindings and this job is still failing, please take a look at the ethereum and foundry versions. We don't pin the versions of these packages in CI so this job may complain after an update of the packages!"
+            git status --porcelain
+            git diff
+            exit 1
+          else
+            echo "✅ Generated files are up to date."
+          fi
 
   test:
     name: Test
