doc: auto-generate documentation

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -40,3 +40,24 @@ jobs:
           go-version: 1.19
       - name: Run tests
         run: make test
+  
+  doc:
+    name: Doc
+    runs-on: ubuntu-latest
+    if: (github.event.action != 'closed' || github.event.pull_request.merged == true)
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-go@v4
+        with:
+          go-version: 1.19
+      - name: Try to update `polycli` documentation
+        run: make gen-doc
+
+      - name: Check if the documentation is up to date
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "❌ Error: Documentation is not up to date. Please run \`make gen-doc\`."
+            exit 1
+          else
+            echo "✅ The documentation is up to date."
+          fi
